# Generated by Django 5.1.7 on 2025-03-15 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChuDe",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name_chu_de", models.CharField(max_length=255)),
                ("noi_dung", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="DanhGia",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nhan_xet", models.TextField()),
                (
                    "idChuDe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.chude"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                ("idFile", models.AutoField(primary_key=True, serialize=False)),
                ("url", models.URLField()),
                (
                    "type",
                    models.CharField(
                        choices=[("image", "Image"), ("docx", "DOCX")], max_length=50
                    ),
                ),
                ("isInput", models.BooleanField(default=False)),
                (
                    "idChuDe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.chude"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserDetail",
            fields=[
                ("idUser", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("google_id", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="User",
        ),
        migrations.AddField(
            model_name="file",
            name="idUser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.userdetail"
            ),
        ),
        migrations.AddField(
            model_name="danhgia",
            name="idUser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.userdetail"
            ),
        ),
    ]
