# Generated by Django 5.1.7 on 2025-03-15 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_danhgia_idthread'),
        ('api', '0003_imageupload'),
    ]

    operations = [
    ]
