# Generated by Django 5.1.7 on 2025-03-15 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_0003_danhgia_idthread_0003_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='danhgia',
            name='soCauHoi',
            field=models.IntegerField(default=0),
        ),
    ]
